@startuml


component DeveloperScripts{
    component GameManager{

    }

    component Generator{

    }

    component MenuManager {

    }

    component PlayerVehicle{

    }

}

component UnityEngine{
    component InputSystem {

    }

    component RenderingSystem{

    }

    component AudioSystem{

    }

    component PhysicsSystem{

    }
}


() VehicleInput as " "
() MenuInput as " "
() Rendering as " "
() Physics as " "
() Audio as " "


InputSystem -- VehicleInput
InputSystem -- MenuInput

VehicleInput "input")-- PlayerVehicle
MenuInput "Touch")-- MenuManager

MenuManager -(0- "Google Play API": request\fetch data
package "Google Play API"{

}

Rendering )-down- DeveloperScripts
Physics )-down- DeveloperScripts
Audio )-down- DeveloperScripts

MenuManager -0)- GameManager
GameManager -(0- Generator
GameManager -(0- PlayerVehicle


RenderingSystem -- Rendering
AudioSystem -- Audio
PhysicsSystem -- Physics




@enduml