@startuml


component DeveloperScripts{
    component GameManager{

    }

    component Generator{

    }

    component MenuManager {

    }

    component PlayerVehicle{

    }

    component Actors{

    }
}

component UnityEngine{
    component InputSystem {

    }

    component RenderingSystem{

    }

    component AudioSystem{

    }

    component PhysicsSystem{

    }
}


() VehicleInput as " "
() MenuInput as " "
() Rendering as " "
() Physics as " "
() Audio as " "


InputSystem -- VehicleInput
InputSystem -- MenuInput

VehicleInput "Steering input")-- PlayerVehicle
VehicleInput "Action button")-- PlayerVehicle
MenuInput "Touch")-- MenuManager

MenuManager <--> "Google Play API": request\fetch data
package "Google Play API"{

}

Rendering )-down- DeveloperScripts
Physics )-down- DeveloperScripts
Audio )-down- DeveloperScripts

MenuManager <--> GameManager: game events
GameManager --> Generator: setup
GameManager <--> PlayerVehicle: game events
GameManager *-- Actors
Generator ..l> Actors: creates

Actors <--> PlayerVehicle: interacts

RenderingSystem -- Rendering
AudioSystem -- Audio
PhysicsSystem -- Physics

@enduml