@startuml


package DeveloperScripts{
    component GameManager{
    }

    component PlayerVehicle{
    }

    component Generator{
    }

    component MenuManager {

    }
}





package UnityEngine{
    component InputSystem {

    }
    component RenderingSystem{

    }

    component AudioSystem{
    }

    component PhysicsSystem{
    }
}


() VehicleInput as " "
() MenuInput as " "
() Rendering as " "
() Physics
() Audio


InputSystem -- VehicleInput
InputSystem -- MenuInput

VehicleInput "Steering input")-- GameManager
VehicleInput "Action button")-- GameManager
MenuInput "Touch")-- MenuManager

RenderingSystem -- Rendering

Rendering )--- DeveloperScripts
Rendering )--- MenuManager

AudioSystem -- Audio

Audio )-- DeveloperScripts
Audio )-- MenuManager

PhysicsSystem -- Physics
Physics )-- GameManager

@enduml