@startuml


component Game{

}


component MenuManager {

}


component GameEngine{
    component InputSystem <<Subsystem>>{

    }
    component RenderingSystem{

    }

    component AudioSystem{

    }

    component PhysicsSystem{
    }
}


() Input
() Rendering
() Physics
() Audio


InputSystem -- Input

Input "Steering input")- Game
Input "Action button")- Game
Input "Touch")- MenuManager

RenderingSystem -- Rendering

Rendering )-- Game
Rendering )-- MenuManager

AudioSystem -- Audio

Audio )-- Game
Audio )-- MenuManager

PhysicsSystem -- Physics
Physics )-- Game


'Czy można uwzględniać tutaj klasy/pakiety czy ma być to tylko abstrakcyjne działanie


@enduml