@startuml
'https://plantuml.com/sequence-diagram

skinparam lifelineStrategy solid
participant UnityEngine
activate UnityEngine
UnityEngine -> PlayerVehicle ++: update()
rnote over PlayerVehicle: game over\ncondition\nfullfiled

PlayerVehicle -> GameManager --++: stop game

GameManager -> GameManager: play game over\nmusic
GameManager -> Generator--++: stop generating
GameManager <-- Generator--++:

GameManager -> UnityEngine--++: stop player input
GameManager <-- UnityEngine--++:

GameManager -> MenuManager --++: game over
MenuManager -> MenuManager : hide joystick and\ndistance meter
MenuManager -> MenuManager : show game over\nmenu
'GameManager <-- MenuManager --++:
'GameManager --> PlayerVehicle--++:
'PlayerVehicle --> UnityEngine--:
MenuManager --> UnityEngine--: returns
UnityEngine -> MenuManager ++: update()
'rnote over MenuManager: player achieved\nbest score
group alt
    MenuManager -> "Google Play API" ++: replace best score
    database "Google Play"
    "Google Play API" -> "Google Play": post highscore
    group alt
        "Google Play API" <-- "Google Play": success
    else
        "Google Play API" <-- "Google Play" : failure
        "Google Play API" --> "MenuManager" : display error message
        "Google Play API" --> UnityEngine -- :returns
    end
else
    "MenuManager" --> UnityEngine --: returns
end



@enduml

