@startuml
'https://plantuml.com/sequence-diagram

skinparam lifelineStrategy solid
participant UnityEngine
activate UnityEngine
rnote across: application during gameplay (player pressed "PLAY" and game started)

UnityEngine -> PlayerVehicle ++: update()
rnote over PlayerVehicle: game over\ncondition\nfullfiled

PlayerVehicle -> GameManager --++: stop game

GameManager -> GameManager: play game over\nmusic
GameManager -> Generator--++: stop generating
GameManager <-- Generator--++:

GameManager -> PlayerVehicle--++: disable steering
GameManager <-- PlayerVehicle--++:

GameManager -> MenuManager --++: game over
MenuManager -> MenuManager : hide joystick and\ndistance meter
MenuManager -> MenuManager : show game over\nmenu
'GameManager <-- MenuManager --++:
'GameManager --> PlayerVehicle--++:
'PlayerVehicle --> UnityEngine--:
MenuManager --> UnityEngine--: return
UnityEngine -> MenuManager ++: update()
'rnote over MenuManager: player achieved\nbest score
alt player achieved new best score
    MenuManager -> "Google Play API" ++: replace highscore
    database "Google Play"
    "Google Play API" -> "Google Play": post highscore
    alt
        "Google Play API" <-- "Google Play": success
    else
        "Google Play API" <-- "Google Play" : failure
        "Google Play API" --> "MenuManager" : display error message
        "Google Play API" --> UnityEngine -- :return
    end
else
    "MenuManager" --> UnityEngine --: return
end



@enduml

