@startuml

state PlayerState : = this is the base state class
state PlayerState : do / control player movement

state PlayerBaseState

[*] -u> PlayerBaseState
PlayerBaseState -l-> PlayerStandardHitState : playerManager [ hasCollided ]
PlayerStandardHitState --d-> PlayerAfterHitState : playerManager

state PlayerStandardHitState : do / apply force to player vehicle

state PlayerAfterHitState{
    [*] -r> invulnerableState
    invulnerableState ---> invulnerableState : [ stateTimeCount < invulnerableTime ]
    invulnerableState ---> PlayerBaseState : [ stateTimeCount >= invulnerableTime ]
}

PlayerBaseState --> PlayerPowerUpReadyState : playerManager [ onPowerUpHit ]

state PlayerPowerUpReadyState{

    state c <<choice>>
    [*] -> c
    c -> playerPowerUp : [ playerPowerUp != null ]
    c --> PlayerBaseState : [ playerPowerUp == null ]

    state playerPowerUp{

        state activePowerUp : do / applies modification on player input
        [*] -> activePowerUp
        activePowerUp -> [*]
        -----

        state passivePowerUp : do / applies modification for a duration
        [*] ->  passivePowerUp
        passivePowerUp -u> passivePowerUp : [ stateTimeCount < powerUpTime ]
        passivePowerUp -l> [*] : [stateTimeCount >= powerUpTime]



    }

}



@enduml