@startuml
'https://plantuml.com/sequence-diagram

autonumber

'just ideas
InputSystem -> MenuManager: Event: play button pressed
MenuManager -> Renderer: Hide menu
MenuManager -> GameManager: Start intro
GameManager -> Renderer: Play intro animation
GameManager -> AudioManager: Play intro music
...

GameManager -> Renderer: Show distance meter and joysticks
GameManager --> InputSystem: Unlock player inputs
GameManager -> AudioManager: Play GameManager music


@enduml
