@startuml
'https://plantuml.com/sequence-diagram

participant UnityEngine
activate UnityEngine

UnityEngine -> MenuManager ++: On "PLAY" button pressed
MenuManager -> MenuManager : Hide menu
MenuManager -> GameManager --++ : Start intro
GameManager->GameManager  : Play intro music
GameManager-> PlayerVehicle --++: Play animation
PlayerVehicle --> UnityEngine : Wait for intro animation end
...
UnityEngine <-- PlayerVehicle --: Intro animation ends
UnityEngine --> GameManager ++: Intro animation ends

GameManager -> GameManager: Show distance meter and joysticks
GameManager -> GameManager: Play level music
GameManager -> PlayerVehicle --++: Unlock player inputs
GameManager <-- PlayerVehicle --++

GameManager --> UnityEngine --: returns


@enduml

